// Generated by gencpp from file robotnik_msgs/MotorsStatusDifferential.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_MESSAGE_MOTORSSTATUSDIFFERENTIAL_H
#define ROBOTNIK_MSGS_MESSAGE_MOTORSSTATUSDIFFERENTIAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robotnik_msgs/MotorStatus.h>
#include <robotnik_msgs/MotorStatus.h>

namespace robotnik_msgs
{
template <class ContainerAllocator>
struct MotorsStatusDifferential_
{
  typedef MotorsStatusDifferential_<ContainerAllocator> Type;

  MotorsStatusDifferential_()
    : lwStatus()
    , rwStatus()  {
    }
  MotorsStatusDifferential_(const ContainerAllocator& _alloc)
    : lwStatus(_alloc)
    , rwStatus(_alloc)  {
  (void)_alloc;
    }



   typedef  ::robotnik_msgs::MotorStatus_<ContainerAllocator>  _lwStatus_type;
  _lwStatus_type lwStatus;

   typedef  ::robotnik_msgs::MotorStatus_<ContainerAllocator>  _rwStatus_type;
  _rwStatus_type rwStatus;




  typedef boost::shared_ptr< ::robotnik_msgs::MotorsStatusDifferential_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotnik_msgs::MotorsStatusDifferential_<ContainerAllocator> const> ConstPtr;

}; // struct MotorsStatusDifferential_

typedef ::robotnik_msgs::MotorsStatusDifferential_<std::allocator<void> > MotorsStatusDifferential;

typedef boost::shared_ptr< ::robotnik_msgs::MotorsStatusDifferential > MotorsStatusDifferentialPtr;
typedef boost::shared_ptr< ::robotnik_msgs::MotorsStatusDifferential const> MotorsStatusDifferentialConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotnik_msgs::MotorsStatusDifferential_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotnik_msgs::MotorsStatusDifferential_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotnik_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'robotnik_msgs': ['/home/summit/catkin_ws_kinetic/src/dependencies/robotnik_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::MotorsStatusDifferential_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::MotorsStatusDifferential_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::MotorsStatusDifferential_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::MotorsStatusDifferential_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::MotorsStatusDifferential_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::MotorsStatusDifferential_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotnik_msgs::MotorsStatusDifferential_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f8b06b08fb9eab82b3a6155a19c6765d";
  }

  static const char* value(const ::robotnik_msgs::MotorsStatusDifferential_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf8b06b08fb9eab82ULL;
  static const uint64_t static_value2 = 0xb3a6155a19c6765dULL;
};

template<class ContainerAllocator>
struct DataType< ::robotnik_msgs::MotorsStatusDifferential_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotnik_msgs/MotorsStatusDifferential";
  }

  static const char* value(const ::robotnik_msgs::MotorsStatusDifferential_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotnik_msgs::MotorsStatusDifferential_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MotorStatus lwStatus\n\
MotorStatus rwStatus\n\
\n\
\n\
================================================================================\n\
MSG: robotnik_msgs/MotorStatus\n\
string state\n\
string status\n\
string statusword\n\
string driveflags\n\
";
  }

  static const char* value(const ::robotnik_msgs::MotorsStatusDifferential_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotnik_msgs::MotorsStatusDifferential_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lwStatus);
      stream.next(m.rwStatus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MotorsStatusDifferential_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotnik_msgs::MotorsStatusDifferential_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotnik_msgs::MotorsStatusDifferential_<ContainerAllocator>& v)
  {
    s << indent << "lwStatus: ";
    s << std::endl;
    Printer< ::robotnik_msgs::MotorStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.lwStatus);
    s << indent << "rwStatus: ";
    s << std::endl;
    Printer< ::robotnik_msgs::MotorStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.rwStatus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTNIK_MSGS_MESSAGE_MOTORSSTATUSDIFFERENTIAL_H
