(cl:defpackage summit_xl_web-srv
  (:use )
  (:export
   "RECORDVIDEO"
   "<RECORDVIDEO-REQUEST>"
   "RECORDVIDEO-REQUEST"
   "<RECORDVIDEO-RESPONSE>"
   "RECORDVIDEO-RESPONSE"
   "GET_CONTROLLER_OPTIONS"
   "<GET_CONTROLLER_OPTIONS-REQUEST>"
   "GET_CONTROLLER_OPTIONS-REQUEST"
   "<GET_CONTROLLER_OPTIONS-RESPONSE>"
   "GET_CONTROLLER_OPTIONS-RESPONSE"
   "SET_CONTROLLER_OPTIONS"
   "<SET_CONTROLLER_OPTIONS-REQUEST>"
   "SET_CONTROLLER_OPTIONS-REQUEST"
   "<SET_CONTROLLER_OPTIONS-RESPONSE>"
   "SET_CONTROLLER_OPTIONS-RESPONSE"
  ))

