// Generated by gencpp from file summit_cpu/Coords.msg
// DO NOT EDIT!


#ifndef SUMMIT_CPU_MESSAGE_COORDS_H
#define SUMMIT_CPU_MESSAGE_COORDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace summit_cpu
{
template <class ContainerAllocator>
struct Coords_
{
  typedef Coords_<ContainerAllocator> Type;

  Coords_()
    : personpresent(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  Coords_(const ContainerAllocator& _alloc)
    : personpresent(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _personpresent_type;
  _personpresent_type personpresent;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;




  typedef boost::shared_ptr< ::summit_cpu::Coords_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::summit_cpu::Coords_<ContainerAllocator> const> ConstPtr;

}; // struct Coords_

typedef ::summit_cpu::Coords_<std::allocator<void> > Coords;

typedef boost::shared_ptr< ::summit_cpu::Coords > CoordsPtr;
typedef boost::shared_ptr< ::summit_cpu::Coords const> CoordsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::summit_cpu::Coords_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::summit_cpu::Coords_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace summit_cpu

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'summit_cpu': ['/home/summit/catkin_ws_kinetic/src/summit_cpu/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::summit_cpu::Coords_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::summit_cpu::Coords_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::summit_cpu::Coords_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::summit_cpu::Coords_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::summit_cpu::Coords_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::summit_cpu::Coords_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::summit_cpu::Coords_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea3ef746517c119e7907675c643db99a";
  }

  static const char* value(const ::summit_cpu::Coords_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea3ef746517c119eULL;
  static const uint64_t static_value2 = 0x7907675c643db99aULL;
};

template<class ContainerAllocator>
struct DataType< ::summit_cpu::Coords_<ContainerAllocator> >
{
  static const char* value()
  {
    return "summit_cpu/Coords";
  }

  static const char* value(const ::summit_cpu::Coords_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::summit_cpu::Coords_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool personpresent\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::summit_cpu::Coords_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::summit_cpu::Coords_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.personpresent);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Coords_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::summit_cpu::Coords_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::summit_cpu::Coords_<ContainerAllocator>& v)
  {
    s << indent << "personpresent: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.personpresent);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUMMIT_CPU_MESSAGE_COORDS_H
