ptz: true
# Internal configuration of the camera. It can instantly flip the camera head 180 degrees and continue to pan beyond its zero point
autoflip: false
# Internal configuration of the camera. It can automatically flip the image electronically 180 degrees, and continue to follow the person in the correct orientation, without delay.
eflip: false
#
pan_joint: joint_camera_pan
tilt_joint: joint_camera_tilt
# degrees
min_pan_value: -170
max_pan_value: 170
min_tilt_value: 0
max_tilt_value: 90

