// Generated by gencpp from file summit_xl_web/get_controller_options.msg
// DO NOT EDIT!


#ifndef SUMMIT_XL_WEB_MESSAGE_GET_CONTROLLER_OPTIONS_H
#define SUMMIT_XL_WEB_MESSAGE_GET_CONTROLLER_OPTIONS_H

#include <ros/service_traits.h>


#include <summit_xl_web/get_controller_optionsRequest.h>
#include <summit_xl_web/get_controller_optionsResponse.h>


namespace summit_xl_web
{

struct get_controller_options
{

typedef get_controller_optionsRequest Request;
typedef get_controller_optionsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_controller_options
} // namespace summit_xl_web


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::summit_xl_web::get_controller_options > {
  static const char* value()
  {
    return "c803d4442092d317a92118964b891b96";
  }

  static const char* value(const ::summit_xl_web::get_controller_options&) { return value(); }
};

template<>
struct DataType< ::summit_xl_web::get_controller_options > {
  static const char* value()
  {
    return "summit_xl_web/get_controller_options";
  }

  static const char* value(const ::summit_xl_web::get_controller_options&) { return value(); }
};


// service_traits::MD5Sum< ::summit_xl_web::get_controller_optionsRequest> should match 
// service_traits::MD5Sum< ::summit_xl_web::get_controller_options > 
template<>
struct MD5Sum< ::summit_xl_web::get_controller_optionsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::summit_xl_web::get_controller_options >::value();
  }
  static const char* value(const ::summit_xl_web::get_controller_optionsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::summit_xl_web::get_controller_optionsRequest> should match 
// service_traits::DataType< ::summit_xl_web::get_controller_options > 
template<>
struct DataType< ::summit_xl_web::get_controller_optionsRequest>
{
  static const char* value()
  {
    return DataType< ::summit_xl_web::get_controller_options >::value();
  }
  static const char* value(const ::summit_xl_web::get_controller_optionsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::summit_xl_web::get_controller_optionsResponse> should match 
// service_traits::MD5Sum< ::summit_xl_web::get_controller_options > 
template<>
struct MD5Sum< ::summit_xl_web::get_controller_optionsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::summit_xl_web::get_controller_options >::value();
  }
  static const char* value(const ::summit_xl_web::get_controller_optionsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::summit_xl_web::get_controller_optionsResponse> should match 
// service_traits::DataType< ::summit_xl_web::get_controller_options > 
template<>
struct DataType< ::summit_xl_web::get_controller_optionsResponse>
{
  static const char* value()
  {
    return DataType< ::summit_xl_web::get_controller_options >::value();
  }
  static const char* value(const ::summit_xl_web::get_controller_optionsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUMMIT_XL_WEB_MESSAGE_GET_CONTROLLER_OPTIONS_H
