// Generated by gencpp from file summit_xl_web/RecordVideoResponse.msg
// DO NOT EDIT!


#ifndef SUMMIT_XL_WEB_MESSAGE_RECORDVIDEORESPONSE_H
#define SUMMIT_XL_WEB_MESSAGE_RECORDVIDEORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace summit_xl_web
{
template <class ContainerAllocator>
struct RecordVideoResponse_
{
  typedef RecordVideoResponse_<ContainerAllocator> Type;

  RecordVideoResponse_()
    : filename()  {
    }
  RecordVideoResponse_(const ContainerAllocator& _alloc)
    : filename(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _filename_type;
  _filename_type filename;




  typedef boost::shared_ptr< ::summit_xl_web::RecordVideoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::summit_xl_web::RecordVideoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RecordVideoResponse_

typedef ::summit_xl_web::RecordVideoResponse_<std::allocator<void> > RecordVideoResponse;

typedef boost::shared_ptr< ::summit_xl_web::RecordVideoResponse > RecordVideoResponsePtr;
typedef boost::shared_ptr< ::summit_xl_web::RecordVideoResponse const> RecordVideoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::summit_xl_web::RecordVideoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::summit_xl_web::RecordVideoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace summit_xl_web

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::summit_xl_web::RecordVideoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::summit_xl_web::RecordVideoResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::summit_xl_web::RecordVideoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::summit_xl_web::RecordVideoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::summit_xl_web::RecordVideoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::summit_xl_web::RecordVideoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::summit_xl_web::RecordVideoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "030824f52a0628ead956fb9d67e66ae9";
  }

  static const char* value(const ::summit_xl_web::RecordVideoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x030824f52a0628eaULL;
  static const uint64_t static_value2 = 0xd956fb9d67e66ae9ULL;
};

template<class ContainerAllocator>
struct DataType< ::summit_xl_web::RecordVideoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "summit_xl_web/RecordVideoResponse";
  }

  static const char* value(const ::summit_xl_web::RecordVideoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::summit_xl_web::RecordVideoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string filename\n\
\n\
";
  }

  static const char* value(const ::summit_xl_web::RecordVideoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::summit_xl_web::RecordVideoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.filename);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RecordVideoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::summit_xl_web::RecordVideoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::summit_xl_web::RecordVideoResponse_<ContainerAllocator>& v)
  {
    s << indent << "filename: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.filename);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUMMIT_XL_WEB_MESSAGE_RECORDVIDEORESPONSE_H
