// Generated by gencpp from file summit_xl_web/RecordVideo.msg
// DO NOT EDIT!


#ifndef SUMMIT_XL_WEB_MESSAGE_RECORDVIDEO_H
#define SUMMIT_XL_WEB_MESSAGE_RECORDVIDEO_H

#include <ros/service_traits.h>


#include <summit_xl_web/RecordVideoRequest.h>
#include <summit_xl_web/RecordVideoResponse.h>


namespace summit_xl_web
{

struct RecordVideo
{

typedef RecordVideoRequest Request;
typedef RecordVideoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RecordVideo
} // namespace summit_xl_web


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::summit_xl_web::RecordVideo > {
  static const char* value()
  {
    return "44be2ad84d20bbc65e2c7c40d2653ffb";
  }

  static const char* value(const ::summit_xl_web::RecordVideo&) { return value(); }
};

template<>
struct DataType< ::summit_xl_web::RecordVideo > {
  static const char* value()
  {
    return "summit_xl_web/RecordVideo";
  }

  static const char* value(const ::summit_xl_web::RecordVideo&) { return value(); }
};


// service_traits::MD5Sum< ::summit_xl_web::RecordVideoRequest> should match 
// service_traits::MD5Sum< ::summit_xl_web::RecordVideo > 
template<>
struct MD5Sum< ::summit_xl_web::RecordVideoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::summit_xl_web::RecordVideo >::value();
  }
  static const char* value(const ::summit_xl_web::RecordVideoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::summit_xl_web::RecordVideoRequest> should match 
// service_traits::DataType< ::summit_xl_web::RecordVideo > 
template<>
struct DataType< ::summit_xl_web::RecordVideoRequest>
{
  static const char* value()
  {
    return DataType< ::summit_xl_web::RecordVideo >::value();
  }
  static const char* value(const ::summit_xl_web::RecordVideoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::summit_xl_web::RecordVideoResponse> should match 
// service_traits::MD5Sum< ::summit_xl_web::RecordVideo > 
template<>
struct MD5Sum< ::summit_xl_web::RecordVideoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::summit_xl_web::RecordVideo >::value();
  }
  static const char* value(const ::summit_xl_web::RecordVideoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::summit_xl_web::RecordVideoResponse> should match 
// service_traits::DataType< ::summit_xl_web::RecordVideo > 
template<>
struct DataType< ::summit_xl_web::RecordVideoResponse>
{
  static const char* value()
  {
    return DataType< ::summit_xl_web::RecordVideo >::value();
  }
  static const char* value(const ::summit_xl_web::RecordVideoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUMMIT_XL_WEB_MESSAGE_RECORDVIDEO_H
