// Generated by gencpp from file summit_xl_web/set_controller_optionsResponse.msg
// DO NOT EDIT!


#ifndef SUMMIT_XL_WEB_MESSAGE_SET_CONTROLLER_OPTIONSRESPONSE_H
#define SUMMIT_XL_WEB_MESSAGE_SET_CONTROLLER_OPTIONSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace summit_xl_web
{
template <class ContainerAllocator>
struct set_controller_optionsResponse_
{
  typedef set_controller_optionsResponse_<ContainerAllocator> Type;

  set_controller_optionsResponse_()
    : ret(false)  {
    }
  set_controller_optionsResponse_(const ContainerAllocator& _alloc)
    : ret(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ret_type;
  _ret_type ret;




  typedef boost::shared_ptr< ::summit_xl_web::set_controller_optionsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::summit_xl_web::set_controller_optionsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct set_controller_optionsResponse_

typedef ::summit_xl_web::set_controller_optionsResponse_<std::allocator<void> > set_controller_optionsResponse;

typedef boost::shared_ptr< ::summit_xl_web::set_controller_optionsResponse > set_controller_optionsResponsePtr;
typedef boost::shared_ptr< ::summit_xl_web::set_controller_optionsResponse const> set_controller_optionsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::summit_xl_web::set_controller_optionsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::summit_xl_web::set_controller_optionsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace summit_xl_web

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::summit_xl_web::set_controller_optionsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::summit_xl_web::set_controller_optionsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::summit_xl_web::set_controller_optionsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::summit_xl_web::set_controller_optionsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::summit_xl_web::set_controller_optionsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::summit_xl_web::set_controller_optionsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::summit_xl_web::set_controller_optionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2cc9e9d8c464550830df49c160979ad";
  }

  static const char* value(const ::summit_xl_web::set_controller_optionsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2cc9e9d8c464550ULL;
  static const uint64_t static_value2 = 0x830df49c160979adULL;
};

template<class ContainerAllocator>
struct DataType< ::summit_xl_web::set_controller_optionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "summit_xl_web/set_controller_optionsResponse";
  }

  static const char* value(const ::summit_xl_web::set_controller_optionsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::summit_xl_web::set_controller_optionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ret\n\
\n\
";
  }

  static const char* value(const ::summit_xl_web::set_controller_optionsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::summit_xl_web::set_controller_optionsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ret);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct set_controller_optionsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::summit_xl_web::set_controller_optionsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::summit_xl_web::set_controller_optionsResponse_<ContainerAllocator>& v)
  {
    s << indent << "ret: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ret);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUMMIT_XL_WEB_MESSAGE_SET_CONTROLLER_OPTIONSRESPONSE_H
